[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Librerías necesarias
lib_deps =
    pololu/QTRSensors @ ^4.0.0

; Configuración para el monitor serie
monitor_speed = 9600
; upload_port = COM9  ; Comentado para auto-detect
