[platformio]
default_envs = espduino32

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    pololu/QTRSensors @ ^4.0.0
monitor_speed = 9600
; upload_port = COM9


[env:espduino32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    pololu/QTRSensors @ ^4.0.0
monitor_speed = 9600
upload_port = COM10
monitor_port = COM10
build_flags =
    -DESP32
